name: Pypi Project
on: push
jobs:
  python-build-m-publisher:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run:  py -m pip install --upgrade pip

      - name: Setup tools
        run: py setup.py sdist

      - name: Uploading the distribution Archives
              Install Twine
        run: py -m pip install --upgrade twine
             py -m twine upload --repository pypi dist/*
       
      - name: Username 
        run: __token__

      - name: Password
        run:  API Token

      - name: View the Uploaded package
        run: https://pypi.org/project/pypibasic/0.0.1/
             pip install pypibasic==0.0.1
    